server:
  port: 6001

spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
#      配置路由
      routes:
        - id: pos-products
#          使用 docker 的容器发现机制
          uri: http://pos-products:8001
#          匹配条件
          predicates:
            - Path=/api/products/**

        - id: pos-carts
          uri: http://pos-carts:9001
          predicates:
            - Path=/api/carts/**

        - id: pos-frontend
          uri: http://pos-frontend:3000
          predicates:
            - Path=/**
